import datetime

# Create your models here.

from django.db import models
from django.utils import timezone

class Question(models.Model):
  content = models.CharField(max_length=255)
  order_id = models.IntegerField()
  question_type = models.IntegerField()
  addtion = models.CharField(max_length=50)
  q_id = models.CharField(max_length=50)
  rev = models.IntegerField()
  short = models.CharField(max_length=50)
  def __str__(self):
    return self.short

class Answer(models.Model):
  time = models.DateTimeField()
  add = models.CharField(max_length=50)
  q101 = models.IntegerField()
  q102 = models.IntegerField()
  q104 = models.IntegerField()
  q103 = models.IntegerField()
  q106 = models.IntegerField()
  q105 = models.IntegerField()
  q107 = models.IntegerField()
  q108 = models.IntegerField()
  q109 = models.IntegerField()
  q111 = models.IntegerField()
  q110 = models.IntegerField()
  q112 = models.IntegerField()
  q113 = models.IntegerField()
  q114 = models.IntegerField()
  q115 = models.IntegerField()
  q117 = models.IntegerField()
  q119 = models.IntegerField()
  q116 = models.IntegerField()
  q120 = models.IntegerField()
  q118 = models.IntegerField()
  q301 = models.IntegerField()
  q302 = models.IntegerField()
  q303 = models.IntegerField()
  q304 = models.IntegerField()
  q305 = models.IntegerField()
  q306 = models.IntegerField()
  q309 = models.IntegerField()
  q307 = models.IntegerField()
  q308 = models.IntegerField()
  q310 = models.IntegerField()
  q311 = models.IntegerField()
  q312 = models.IntegerField()
  q313 = models.IntegerField()
  q314 = models.IntegerField()
  q316 = models.IntegerField()
  q317 = models.IntegerField()
  q318 = models.IntegerField()
  q319 = models.IntegerField()
  q320 = models.IntegerField()
  q315 = models.IntegerField()
  q201 = models.IntegerField()
  q202 = models.IntegerField()
  q203 = models.IntegerField()
  q204 = models.IntegerField()
  q205 = models.IntegerField()
  q206 = models.IntegerField()
  q207 = models.IntegerField()
  q208 = models.IntegerField()
  q209 = models.IntegerField()
  q210 = models.IntegerField()
  q1001 = models.CharField(max_length=255)
  q1002 = models.CharField(max_length=255)
  q1003 = models.CharField(max_length=255)
  q1004 = models.CharField(max_length=255)
  ip = models.CharField(max_length=255)
  device = models.CharField(max_length=255)
